apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels: {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.server.port }}
    name: server
  selector: {{- include "chart.selectorLabels" . | nindent 4 }}
